networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=110101
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      custom:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
    networks:
      custom:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      custom:
  auction-svc:
    image: dionupton/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;User Id=postgres;Password=110101;Database=auctions
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__Webapi__Protocols=Http1
      - Kestrel__Endpoints__Webapi__Url=http://+:80
    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - postgres
      - rabbitmq
    networks:
      custom:
  search-svc:
    image: dionupton/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      custom:
  identity-svc:
    image: dionupton/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;User Id=postgres;Password=110101;Database=identitydb
      - VIRTUAL_HOST=id.flogit.com
      - ClientApp=https://app.flogit.com
    depends_on:
      - postgres
    networks:
      custom:
         ipv4_address: 10.5.0.200
    ports:
      - 5000:80
  gateway-svc:
    image: dionupton/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=https://app.flogit.com
      - VIRTUAL_HOST=api.flogit.com
    ports:
      - 6001:80
    networks:
      custom:
  bid-svc:
    image: dionupton/bid-svc:latest
    build:
      context: .
      dockerfile: src/BiddingService/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuction=http://auction-svc:7777
    ports:
      - 7003:80
    depends_on:
      - mongodb
      - rabbitmq 
    networks:
      custom: 
  py-svc:
    image: dionupton/py-svc:latest
    volumes:
      - ./data:/data
    networks:
      custom:
    environment:
      - GATEWAY_API_URL=http://gateway-svc
      - IDENTITY_URL=http://identity-svc
    build:
      context: .
      dockerfile: py/dockerfile  
    depends_on:
      - gateway-svc
      - identity-svc
    command: python3 py/bot.py
  notify-svc:
    image: dionupton/notify-svc:latest
    build:
      context: .
      dockerfile: src/NotificationService/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:80
    depends_on:
      - rabbitmq 
    networks:
      custom:
  webapp:
    image: dionupton/webapp
    build:
      context: .
      dockerfile: frontend/webapp/dockerfile
    volumes:
      - /var/lib/web/data
    extra_hosts:
      - id.flogit.com:10.5.0.200
    environment:
      - NEXTAUTH_SECRET=somethingreallysecret
      - NEXTAUTH_URL=http://app.flogit.com
      - NEXTAUTH_URL_INTERNAL=http://webapp:3000
      - API_URL=http://gateway-svc/
      - ID_URL=http://id.flogit.com
      - NEXT_PUBLIC_NOTIFY_URL=http://gateway-svc/notifications 
      - VIRTUAL_HOST=app.flogit.com
      - VIRTUAL_PORT=3000
    networks:
      custom:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      custom:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs
    depends_on:
      - webapp
      - gateway-svc
      - identity-svc
    