# fly.toml app configuration file generated for floral-sunset-4984 on 2023-09-12T22:57:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "floral-sunset-4984"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 5000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
